apiVersion: v1
kind: ServiceAccount
metadata:
  name: stuck-pod-cleaner
  namespace: {{ .Values.namespace }}
  labels:
    app: stuck-pod-cleaner
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stuck-pod-cleaner-role
  labels:
    app: stuck-pod-cleaner
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "delete", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stuck-pod-cleaner-binding
  labels:
    app: stuck-pod-cleaner
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: stuck-pod-cleaner
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: stuck-pod-cleaner-role
  apiGroup: rbac.authorization.k8s.io